### PR TITLE
Enhancement: Updated Crawler with Improved Functionality

### PR DESCRIPTION
**Pull request by kevinrodd**
This pull request enhances the HelloFreshCrawler with several improvements and new features to make it more robust and user-friendly.

**Changes Made:**

1. **Fixed Access Token Fetch:** Corrected the access_token fetch process to ensure seamless authentication.

2. **Added Retries:** Implemented a retry mechanism for downloading recipes, handling connection timeouts and other potential issues with resilience.

3. **Added Delay Between Batch Downloads/Retries:** Introduced a delay between batch downloads and retries to prevent server overload and improve reliability.

4. **Added DE Locale Support:** Enhanced the crawler to support recipes in the German (DE) language, expanding its usability.

5. **Improved Console.log Output:** Made improvements to the console.log output for better user feedback and debugging.

6. **Updated README:** Updated the README to reflect the new language support and provide clear usage instructions.

**Reason for Changes:**
These changes were made to enhance the functionality and user experience of the HelloFreshCrawler. By addressing access_token issues, adding retries and delays, supporting additional locales, improving console output, and updating documentation, we make the crawler more reliable, user-friendly, and versatile.

**Testing Done:**
I have thoroughly tested these changes to ensure that the crawler works as expected, including scenarios with retries and different locales.

**Checklist:**
- [x] Code has been reviewed locally.
- [x] Documentation (README) has been updated to reflect the changes.
- [x] All code is properly formatted and follows best practices.
- [x] The pull request is linked to any relevant issues or feature requests.

**Additional Comments:**
I'm open to feedback and discussions regarding these changes. Please let me know if there are any further improvements or adjustments that should be made.

Thank you for considering this pull request!

### CODE REVIEW

**Comment by alexcodito** [comment]
Thank you for your comprehensive and well-written PR. I've added a comment suggestion, but I'm fine with merging either way.

**Comment by kevinrodd** [comment]
Thanks for the reply. I've corrected the README with the correct usage command but i can't find your comment suggestion you mentioned.

**Comment by kevinrodd** [comment]
Got any updates?

**Comment by kevinrodd** [comment]
@alexcodito Would you merge, please?

**Review by alexcodito — CHANGES_REQUESTED** [review]
I'm really not a fan of using escape characters to change the color of the console. Is there any chance you could use a package, or at least add the following to the utils folder like below?

```
const colours = {
    reset: "\x1b[0m",
    bright: "\x1b[1m",
    dim: "\x1b[2m",
    underscore: "\x1b[4m",
    blink: "\x1b[5m",
    reverse: "\x1b[7m",
    hidden: "\x1b[8m",
    
    fg: {
        black: "\x1b[30m",
        red: "\x1b[31m",
        green: "\x1b[32m",
        yellow: "\x1b[33m",
        blue: "\x1b[34m",
        magenta: "\x1b[35m",
        cyan: "\x1b[36m",
        white: "\x1b[37m",
        gray: "\x1b[90m",
        crimson: "\x1b[38m" // Scarlet
    },
    bg: {
        black: "\x1b[40m",
        red: "\x1b[41m",
        green: "\x1b[42m",
        yellow: "\x1b[43m",
        blue: "\x1b[44m",
        magenta: "\x1b[45m",
        cyan: "\x1b[46m",
        white: "\x1b[47m",
        gray: "\x1b[100m",
        crimson: "\x1b[48m"
    }
};
```

Usage:
`console.log(colours.bg.blue, colours.fg.white, "White message with a blue background", colours.reset) ; `

There are several places where this applies.

**Comment by alexcodito** [comment]
> @alexcodito Would you merge, please?

Apologies, I've been unavailable recently. I'm not sure why my comment/feedback isn't showing up, but I've submitted it again now. I'm not too precious the requested change, but I think it would look better. I'll leave the decision with you.

**Comment by kevinrodd** [comment]
No worries! Thanks for the suggestion. I've updated the code, please check if it's okay for you.

**Comment by kevinrodd** [comment]
push

**Review by alexcodito — APPROVED** [review]

**Pull request merged**
